from django.test import TestCase
from rest_framework.test import APIClient


class TestQuote(TestCase):
    def setUp(self):
        self.quote = {
            "effective_date": "2021-01-01T01:01:00Z",
            "property_mileage_to_nearest_volcano": 20,
            "is_previous_policy_cancelled": False,
            "is_property_to_be_insured_owner": False,
            "address_line1": "123 Elm Street",
            "address_line2": None,
            "city": "Nashville",
            "state": "TN",
            "zip_code": 37221,
        }

    # test for success
    def test_quote_returns_201(self):
        client = APIClient()

        response = client.post("/quotes/", self.quote, format="json")

        self.assertEqual(response.status_code, 201)

        quote_number = response.data.get("quote_number")
        self.assertIsNotNone(quote_number)
        self.assertEqual(len(quote_number), 36)

        pass

    # test for an autogenerated uuid
    def test_quote_uuid(self):
        client = APIClient()

        response = client.post("/quotes/", self.quote, format="json")

        quote_number = response.data.get("quote_number")
        self.assertIsNotNone(quote_number)
        self.assertEqual(len(quote_number), 36)
