# Generated by Django 3.2.5 on 2021-07-20 23:23

from django.db import migrations, models
import quotes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(default=quotes.models.get_uuid, max_length=32),
                ),
                ("effective_date", models.DateTimeField()),
                ("property_mileage_to_nearest_volcano", models.IntegerField()),
                ("is_previous_policy_cancelled", models.BooleanField(default=False)),
                ("is_property_to_be_insured_owner", models.BooleanField(default=False)),
                ("line1", models.CharField(max_length=300)),
                ("line2", models.CharField(blank=True, max_length=3000, null=True)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("zip_code", models.IntegerField()),
            ],
            options={
                "ordering": ["effective_date"],
            },
        ),
    ]
