# Generated by Django 3.2.5 on 2021-07-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Premium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term_premium", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "monthly_premium",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "total_additional_fees",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "total_monthly_fees",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "total_discounts",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "total_monthly_discounts",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="quote",
            old_name="line1",
            new_name="address_line1",
        ),
        migrations.RenameField(
            model_name="quote",
            old_name="line2",
            new_name="address_line2",
        ),
    ]
